# Site configuration
title: Chris Harris
email: chris.m.harris@gmail.com
description: >-
  Just my contact info and a little blog
baseurl: ""
url: "https://loosepin313.github.io"
twitter_username: dont do twitter
github_username: loosepin313

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/:year/:month/:day/:title/"

# Collections
collections:
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title/
